package proyectofinalp2_jorgeeuceda;

import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());
    private ArrayList<Variable> variables = new ArrayList<>();
    private Point defaultPosition = null;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        DefaultListModel model = new DefaultListModel();
        lst_variables.setModel(model);
        defaultPosition = lbl_move.getLocation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popmnu_edit = new javax.swing.JPopupMenu();
        itm_cambiarColor = new javax.swing.JMenuItem();
        itm_cambiarTexto = new javax.swing.JMenuItem();
        itm_eliminar = new javax.swing.JMenuItem();
        itm_cambiarFuente = new javax.swing.JMenuItem();
        itm_propiedades = new javax.swing.JMenuItem();
        itm_copiar = new javax.swing.JMenuItem();
        itm_agregarPropiedad = new javax.swing.JMenuItem();
        itm_colorFuente = new javax.swing.JMenuItem();
        frm_agregarVariable = new javax.swing.JFrame();
        pnl_agregarVariable = new javax.swing.JPanel();
        lbl_variable = new javax.swing.JLabel();
        txt_variableNombre = new javax.swing.JTextField();
        lbl_valor = new javax.swing.JLabel();
        lbl_tipo = new javax.swing.JLabel();
        box_tipo = new javax.swing.JComboBox<>();
        btn_nuevaVariable = new javax.swing.JButton();
        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_variables = new javax.swing.JList<>();
        lbl_variables = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        toolBar = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_move = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tab_diagrama = new javax.swing.JPanel();
        tab_codigo = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        tab_archivo = new javax.swing.JMenu();
        itm_guardar = new javax.swing.JMenuItem();
        itm_abrir = new javax.swing.JMenuItem();
        itm_nuevo = new javax.swing.JMenuItem();
        tab_exportar = new javax.swing.JMenu();
        itm_savePDF = new javax.swing.JMenuItem();

        popmnu_edit.setComponentPopupMenu(popmnu_edit);
        popmnu_edit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        itm_cambiarColor.setText("Cambiar Color");
        popmnu_edit.add(itm_cambiarColor);

        itm_cambiarTexto.setText("Cambiar el Texto");
        itm_cambiarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_cambiarTextoActionPerformed(evt);
            }
        });
        popmnu_edit.add(itm_cambiarTexto);

        itm_eliminar.setText("Eliminar");
        itm_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_eliminarActionPerformed(evt);
            }
        });
        popmnu_edit.add(itm_eliminar);

        itm_cambiarFuente.setText("Cambiar Fuente");
        popmnu_edit.add(itm_cambiarFuente);

        itm_propiedades.setText("Propiedades");
        popmnu_edit.add(itm_propiedades);

        itm_copiar.setText("Copiar");
        popmnu_edit.add(itm_copiar);

        itm_agregarPropiedad.setText("Agregar Propiedad");
        popmnu_edit.add(itm_agregarPropiedad);

        itm_colorFuente.setText("Editar Color de Fuente");
        popmnu_edit.add(itm_colorFuente);

        lbl_variable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbl_variable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_variable.setText("Crear Variable");
        lbl_variable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_valor.setText("Nombre:");

        lbl_tipo.setText("Tipo:");

        box_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Integer", "Double", "Float", "Short", "Long", "Byte", "String", "Character", "Boolean" }));

        btn_nuevaVariable.setText("Agregar Variable");
        btn_nuevaVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevaVariableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_agregarVariableLayout = new javax.swing.GroupLayout(pnl_agregarVariable);
        pnl_agregarVariable.setLayout(pnl_agregarVariableLayout);
        pnl_agregarVariableLayout.setHorizontalGroup(
            pnl_agregarVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_agregarVariableLayout.createSequentialGroup()
                .addGroup(pnl_agregarVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_agregarVariableLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnl_agregarVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl_agregarVariableLayout.createSequentialGroup()
                                .addComponent(lbl_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(box_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnl_agregarVariableLayout.createSequentialGroup()
                                .addComponent(lbl_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_variableNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnl_agregarVariableLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btn_nuevaVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_agregarVariableLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(lbl_variable)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pnl_agregarVariableLayout.setVerticalGroup(
            pnl_agregarVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_agregarVariableLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbl_variable)
                .addGap(30, 30, 30)
                .addGroup(pnl_agregarVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_variableNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_valor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_agregarVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tipo)
                    .addComponent(box_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btn_nuevaVariable)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frm_agregarVariableLayout = new javax.swing.GroupLayout(frm_agregarVariable.getContentPane());
        frm_agregarVariable.getContentPane().setLayout(frm_agregarVariableLayout);
        frm_agregarVariableLayout.setHorizontalGroup(
            frm_agregarVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_agregarVariable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frm_agregarVariableLayout.setVerticalGroup(
            frm_agregarVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_agregarVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setComponentPopupMenu(popmnu_edit);

        jScrollPane1.setViewportView(lst_variables);

        lbl_variables.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbl_variables.setText("Variables");

        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        toolBar.setRollover(true);

        jLabel2.setText("Fuente");
        toolBar.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("Opciones:");

        lbl_move.setBackground(new java.awt.Color(0, 0, 0));
        lbl_move.setForeground(new java.awt.Color(255, 255, 255));
        lbl_move.setText("WHUT");
        lbl_move.setOpaque(true);
        lbl_move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbl_moveMouseDragged(evt);
            }
        });
        lbl_move.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_moveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_moveMouseReleased(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tab_diagrama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab_diagramaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab_diagramaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout tab_diagramaLayout = new javax.swing.GroupLayout(tab_diagrama);
        tab_diagrama.setLayout(tab_diagramaLayout);
        tab_diagramaLayout.setHorizontalGroup(
            tab_diagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );
        tab_diagramaLayout.setVerticalGroup(
            tab_diagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Diagrama", tab_diagrama);

        javax.swing.GroupLayout tab_codigoLayout = new javax.swing.GroupLayout(tab_codigo);
        tab_codigo.setLayout(tab_codigoLayout);
        tab_codigoLayout.setHorizontalGroup(
            tab_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );
        tab_codigoLayout.setVerticalGroup(
            tab_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Codigo", tab_codigo);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbl_move, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                            .addComponent(lbl_variables)
                            .addGap(42, 42, 42))))
                .addGap(18, 18, 18))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_move, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_variables, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_agregar)))
                .addContainerGap())
        );

        tab_archivo.setText("Archivo");

        itm_guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itm_guardar.setText("Guardar");
        itm_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_guardarActionPerformed(evt);
            }
        });
        tab_archivo.add(itm_guardar);

        itm_abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itm_abrir.setText("Abrir");
        tab_archivo.add(itm_abrir);

        itm_nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itm_nuevo.setText("Nuevo");
        tab_archivo.add(itm_nuevo);

        menuBar.add(tab_archivo);

        tab_exportar.setText("Exportar");

        itm_savePDF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itm_savePDF.setText("Guardar PDF");
        tab_exportar.add(itm_savePDF);

        menuBar.add(tab_exportar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itm_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_guardarActionPerformed

    private void itm_cambiarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_cambiarTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_cambiarTextoActionPerformed

    private void itm_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_eliminarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        frm_agregarVariable.setVisible(true);
        frm_agregarVariable.setSize(400,255);
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_nuevaVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevaVariableActionPerformed
        String nombre = txt_variableNombre.getText();
        String tipo = (String) box_tipo.getSelectedItem();
        System.out.println(tipo);
        
        boolean nombreValid = true;
        
        if(!Character.isAlphabetic(nombre.charAt(0))){
            nombreValid = false;
        }
        
        for (int i = 0; i < nombre.length(); i++) {
            if (Character.isSpaceChar(nombre.charAt(i))) {
                nombreValid = false;
            }
        }
        
        if(nombreValid){
            Variable variable = new Variable(nombre, tipo);
            variables.add(variable);
            DefaultListModel model = (DefaultListModel)lst_variables.getModel();
            model.addElement(variable);
            JOptionPane.showMessageDialog(null, "Variable Creada");
        }
        else{
            JOptionPane.showMessageDialog(null, "Nombre Invalido");
        }
    }//GEN-LAST:event_btn_nuevaVariableActionPerformed

    private void lbl_moveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_moveMousePressed
        
    }//GEN-LAST:event_lbl_moveMousePressed

    private void lbl_moveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_moveMouseReleased
        
    }//GEN-LAST:event_lbl_moveMouseReleased

    private void lbl_moveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_moveMouseDragged
        Point mouseLocation = MouseInfo.getPointerInfo().getLocation();
        SwingUtilities.convertPointFromScreen(mouseLocation, background);
        JLabel thisLabel = lbl_move;
        lbl_move.setLocation(mouseLocation);
    }//GEN-LAST:event_lbl_moveMouseDragged

    private void tab_diagramaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_diagramaMouseEntered

    }//GEN-LAST:event_tab_diagramaMouseEntered

    private void tab_diagramaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_diagramaMouseExited

        
    }//GEN-LAST:event_tab_diagramaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JComboBox<String> box_tipo;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_nuevaVariable;
    private javax.swing.JFrame frm_agregarVariable;
    private javax.swing.JMenuItem itm_abrir;
    private javax.swing.JMenuItem itm_agregarPropiedad;
    private javax.swing.JMenuItem itm_cambiarColor;
    private javax.swing.JMenuItem itm_cambiarFuente;
    private javax.swing.JMenuItem itm_cambiarTexto;
    private javax.swing.JMenuItem itm_colorFuente;
    private javax.swing.JMenuItem itm_copiar;
    private javax.swing.JMenuItem itm_eliminar;
    private javax.swing.JMenuItem itm_guardar;
    private javax.swing.JMenuItem itm_nuevo;
    private javax.swing.JMenuItem itm_propiedades;
    private javax.swing.JMenuItem itm_savePDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_move;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JLabel lbl_valor;
    private javax.swing.JLabel lbl_variable;
    private javax.swing.JLabel lbl_variables;
    private javax.swing.JList<String> lst_variables;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel pnl_agregarVariable;
    private javax.swing.JPopupMenu popmnu_edit;
    private javax.swing.JMenu tab_archivo;
    private javax.swing.JPanel tab_codigo;
    private javax.swing.JPanel tab_diagrama;
    private javax.swing.JMenu tab_exportar;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JTextField txt_variableNombre;
    // End of variables declaration//GEN-END:variables
}
